const pictures = [
    { id: 1, src: 'assets/Events/NSS24/1.jpg', text: "National Service Scheme(NSS)-24" },
    { id: 2, src: 'assets/Events/NSS24/2.jpg', text: "National Service Scheme(NSS)-24" },
    { id: 3, src: 'assets/Events/NSS24/3.jpg', text: "National Service Scheme(NSS)-24" },
    { id: 4, src: 'assets/Events/NSS24/4.jpg', text: "National Service Scheme(NSS)-24" },
    { id: 5, src: 'assets/Events/NSS24/5.jpg', text: "National Service Scheme(NSS)-24" },
    { id: 6, src: 'assets/Events/FOODIES/1.jpg', text: "Foodies.AI" },
    { id: 7, src: 'assets/Events/FOODIES/2.jpg', text: "Foodies.AI" },
    { id: 8, src: 'assets/Events/FOODIES/3.jpg', text: "Foodies.AI" },
    { id: 9, src: 'assets/Events/QuoteThePrize/1.jpg', text: "Quote The Price" },
    { id: 10, src: 'assets/Events/QuoteThePrize/2.jpg', text: "Quote The Price" },
    { id: 11, src: 'assets/Events/QuoteThePrize/3.jpg', text: "Quote The Price" },
    { id: 12, src: 'assets/Events/QuoteThePrize/4.jpg', text: "Quote The Price" },
    { id: 13, src: 'assets/Events/QuoteThePrize/5.jpg', text: "Quote The Price" },
    { id: 14, src: 'assets/Events/TechnoVIT/1.jpg', text: "TechnoVIT" },
    { id: 15, src: 'assets/Events/TechnoVIT/2.jpg', text: "TechnoVIT" },
    { id: 16, src: 'assets/Events/TechnoVIT/3.jpg', text: "TechnoVIT" },
    { id: 17, src: 'assets/Events/TechnoVIT/4.jpg', text: "TechnoVIT" },
    { id: 18, src: 'assets/Events/Synthetix23/1.jpg', text: "Synthetix'23" },
    { id: 19, src: 'assets/Events/Synthetix23/2.jpg', text: "Synthetix'23" },
    { id: 20, src: 'assets/Events/Synthetix23/3.jpeg', text: "Synthetix'23" },
    { id: 21, src: 'assets/Events/Synthetix23/4.jpeg', text: "Synthetix'23" },
    { id: 22, src: 'assets/Events/NSS23/1.jpg', text: "National Service Scheme(NSS)-23" },
    { id: 23, src: 'assets/Events/NSS23/2.JPG', text: "National Service Scheme(NSS)-23" },
    { id: 24, src: 'assets/Events/NSS23/1.jpg', text: "National Service Scheme(NSS)-23" },
    { id: 25, src: 'assets/Events/NSS23/2.JPG', text: "National Service Scheme(NSS)-23" },
    { id: 26, src: 'assets/Events/Flipkart/1.jpeg', text: "Flipkart Grid" },
    { id: 27, src: 'assets/Events/Flipkart/2.jpeg', text: "Flipkart Grid" },
    { id: 28, src: 'assets/Events/Flipkart/3.jpeg', text: "Flipkart Grid" },
    { id: 29, src: 'assets/Events/Flipkart/4.jpeg', text: "Flipkart Grid" },
];

export default pictures;